<?php

defined( 'ABSPATH' ) || exit;

return array(
	'css' => array(

		'fonts'      => 'https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Cinzel:wght@600;700;800;900&family=Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700&family=Dancing+Script:wght@400..700&family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Lora:ital,wght@0,400..700;1,400..700&family=Metal+Mania&family=Patua+One&family=Playfair+Display:ital,wght@0,600;0,800;0,900;1,600;1,800;1,900&family=Rubik+Dirt&family=Rubik+Distressed&display=swap',

		'variables'  => 'assets/css/variables.css',
		'base'       => 'assets/css/base.css',
		'layout'     => 'assets/css/layout.css',
		'frame'      => 'assets/css/frame.css',
		'textures'   => 'assets/css/textures.css',
		'shape'      => 'assets/css/shape.css',
		'animations' => 'assets/css/animations.css',

		'ui-button'     => 'assets/css/components/button.css',
		'ui-card'       => 'assets/css/components/card.css',
		'ui-form'       => 'assets/css/components/form.css',
		'ui-badge'      => 'assets/css/components/badge.css',
		'ui-logo'       => 'assets/css/components/logo.css',
		'ui-navigation' => 'assets/css/components/navigation.css',
		'ui-header'     => 'assets/css/components/header.css',
		'ui-mobile-nav' => 'assets/css/components/mobile-nav.css',
		'ui-footer'     => 'assets/css/components/footer.css',
		'ui-scroll-top' => 'assets/css/components/scroll-top.css',
		'ui-floating-whatsapp' => 'assets/css/components/floating-whatsapp.css',
		'ui-marquee'    => 'assets/css/components/marquee.css',
		'ui-table'      => 'assets/css/components/table.css',
		'ui-list'       => 'assets/css/components/list.css',
		'ui-dialog'     => 'assets/css/components/dialog.css',
		'ui-custom-select' => 'assets/css/components/custom-select.css',
		'ui-alert'      => 'assets/css/components/alert.css',
		'ui-toast'      => 'assets/css/components/toast.css',
		'ui-dropdown'   => 'assets/css/components/dropdown.css',
		'ui-tooltip'    => 'assets/css/components/tooltip.css',
		'ui-faq'        => 'assets/css/components/faq.css',
		'ui-banner'     => 'assets/css/components/banner.css',
		'ui-stats'      => 'assets/css/components/stats.css',
		'ui-testimonial-card' => 'assets/css/components/testimonial-card.css',
		'ui-stamp'            => 'assets/css/components/stamp.css',
		'ui-section-header'   => 'assets/css/components/section-header.css',
		'ui-cta-banner'       => 'assets/css/components/cta-banner.css',
		'ui-process-steps'    => 'assets/css/components/process-steps.css',
		'ui-gallery'          => 'assets/css/components/gallery.css',

		'ui-carousel-controls' => 'assets/css/components/carousel-controls.css',
		'ui-hero-carousel'    => 'assets/css/components/hero-carousel.css',
		'ui-video-testimonial-card'     => 'assets/css/components/video-testimonial-card.css',
		'ui-video-testimonial-carousel' => 'assets/css/components/video-testimonial-carousel.css',
		'ui-hero'         => 'assets/css/components/hero.css',
		'ui-feature-row'  => 'assets/css/components/feature-row.css',
		'ui-certificate-carousel' => 'assets/css/components/certificate-carousel.css',
		'ui-product-list'         => 'assets/css/components/product-list.css',
		'ui-step-chain'           => 'assets/css/components/step-chain.css',
		'ui-booking-wizard'       => 'assets/css/components/booking-wizard.css',
		'ui-photo-stamp'          => 'assets/css/components/photo-stamp.css',
		'ui-photo-grid'           => 'assets/css/components/photo-grid.css',
		'ui-showcase'             => 'assets/css/components/showcase.css',
		'ui-section-nav'          => 'assets/css/components/section-nav.css',
		'ui-loader'               => 'assets/css/components/loader.css',
		'ui-cookie-consent'       => 'assets/css/components/cookie-consent.css',
		'ui-feature-sections'     => 'assets/css/components/feature-sections.css',
		'ui-occasions'            => 'assets/css/components/occasions.css',
		'cmsplugstylesoverride'   => 'assets/css/cmsplugstylesoverride.css',
		'page-home'     => 'assets/css/pages/home.css',
		'page-history'  => 'assets/css/pages/history.css',
		'page-about'    => 'assets/css/pages/about.css',
		'page-contact'  => 'assets/css/pages/contact.css',
		'page-search'   => 'assets/css/pages/search.css',

		'utilities'     => 'assets/css/utilities.css',

		'shape'         => 'assets/css/shape.css',

		'memory-card'   => 'assets/css/memory-card.css',

		'textures'      => 'assets/css/textures.css',
	),
	'js' => array(

		'core-utils'  => 'assets/js/core/utils.js',
		'core-dom'    => 'assets/js/core/dom.js',
		'core-events' => 'assets/js/core/events.js',
		'core-app'    => 'assets/js/core/app.js',
		'core-reveal' => 'assets/js/core/reveal.js',
		'core-parallax' => 'assets/js/core/parallax.js',

		'ui-dialog'   => 'assets/js/components/dialog.js',
		'ui-custom-select' => 'assets/js/components/custom-select.js',
		'ui-alert'    => 'assets/js/components/alert.js',
		'ui-toast'    => 'assets/js/components/toast.js',
		'ui-dropdown'    => 'assets/js/components/dropdown.js',
		'ui-tooltip'     => 'assets/js/components/tooltip.js',
		'ui-mobile-nav'  => 'assets/js/components/mobile-nav.js',
		'ui-scroll-top'  => 'assets/js/components/scroll-top.js',
		'ui-section-nav' => 'assets/js/components/section-nav.js',
		'ui-faq'         => 'assets/js/components/faq.js',
		'ui-gallery'     => 'assets/js/components/gallery.js',
		'ui-hero'             => 'assets/js/components/hero.js',
		'ui-hero-carousel'    => 'assets/js/components/hero-carousel.js',
		'ui-video-testimonial-card'     => 'assets/js/components/video-testimonial-card.js',
		'ui-video-testimonial-carousel' => 'assets/js/components/video-testimonial-carousel.js',
		'ui-certificate-carousel' => 'assets/js/components/certificate-carousel.js',
		'ui-showcase'             => 'assets/js/components/showcase.js',
		'ui-booking-wizard'       => 'assets/js/components/booking-wizard.js',
		'ui-loader'               => 'assets/js/components/loader.js',
		'ui-card-stream'          => 'assets/js/components/card-stream.js',
		'ui-vintage-carousel'     => 'assets/js/components/vintage-carousel.js',
		'ui-live-badge'           => 'assets/js/components/live-badge.js',
		'ui-cookie-consent'       => 'assets/js/components/cookie-consent.js',
		'ui-sticky-sidebar'       => 'assets/js/components/sticky-sidebar.js',
		'ui-logo-strip-marquee'   => 'assets/js/components/logo-strip-marquee.js',
		'ui-occasions'            => 'assets/js/components/occasions.js',
	),
);
